import { Inter } from "next/font/google";
import "./globals.css";

import SessionWrapper from "@/components/SessionWrapper/SessionWrapper";
import ReduxProvider from "@/components/ReduxProvider/ReduxProvider";
import Nav from "@/components/Nav/Nav";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionWrapper>
          <ReduxProvider>
            <Nav />
            {children}
          </ReduxProvider>
        </SessionWrapper>
      </body>
    </html>
  );
}
